---
zabbix_version: "7.0.0"

zabbix_user: zabbix

zabbix_group: zabbix

zabbix_source_dir: /usr/local/src

zabbix_source_path: "{{ zabbix_source_dir }}/zabbix-{{ zabbix_version }}"

zabbix_install_prefix: /usr/local