---
zabbix_version: "7.0.0"

zabbix_user: zabbix
zabbix_group: zabbix

zabbix_source_dir: /usr/local/src
zabbix_install_prefix: /usr/local


zabbix_db_host: 192.168.56.20
zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_password: ChangeMeLater


zabbix_server_listen_port: 10051

zabbix_agent_server: 192.168.56.30

zabbix_schema_file: "{{ zabbix_source_path }}/database/postgresql/server.sql.gz"