---
# defaults file for roles/postgresql

postgresql_version: 17

postgresql_packages:
  - postgresql17-server
  - postgresql17
  - postgresql17-contrib

postgresql_service: postgresql-17

postgresql_port: 5432

postgresql_database: zabbix

postgresql_user: zabbix

postgresql_password: ChangeMeLater

postgresql_listen_addresses: "*"

postgresql_allowed_hosts:
  - 192.168.56.30