---
- name: Prepare Zabbix Source Build Environment
  hosts: monitoring
  become: true

  roles:
    - zabbix-build

- name: Deploy Zabbix Web UI
  hosts: monitoring
  become: true
  roles:
    - role: zabbix-web
      tags:
        - web  