- name: Create Zabbix host via API
  community.zabbix.zabbix_host:
    server_url: http://192.168.56.30/zabbix/api_jsonrpc.php
    login_user: Admin
    login_password: zabbix
    host_name: mon01
    visible_name: mon01
    groups:
      - Templates/Servers
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: 192.168.56.30
        dns: ''
        port: 10050
    state: present
  tags:
    - config