---
- name: Verify Zabbix PostgreSQL schema directory exists
  ansible.builtin.stat:
    path: "{{ zabbix_schema_dir }}"
  register: zabbix_schema_dir_check
  tags:
    - database


- name: Fail if PostgreSQL schema directory missing
  ansible.builtin.fail:
    msg: "Zabbix PostgreSQL schema directory not found"
  when: not zabbix_schema_dir_check.stat.exists
  tags:
    - database


- name: Import Zabbix PostgreSQL schema
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "{{ zabbix_schema_dir }}/{{ item }}"
  become_user: postgres
  delegate_to: "{{ zabbix_db_host }}"
  loop:
    - schema.sql
    - images.sql
    - data.sql
  tags:
    - database
    