---
- name: Generate Zabbix database schema
  ansible.builtin.command:
    cmd: make dbschema
    chdir: "{{ zabbix_source_path }}"
    creates: "{{ zabbix_source_path }}/database/postgresql/schema.sql"
  tags:
    - database


- name: Verify PostgreSQL schema file exists
  ansible.builtin.stat:
    path: "{{ zabbix_source_path }}/database/postgresql/schema.sql"
  register: zabbix_schema
  tags:
    - database


- name: Fail if PostgreSQL schema is missing
  ansible.builtin.fail:
    msg: "Zabbix PostgreSQL schema was not generated"
  when: not zabbix_schema.stat.exists
  tags:
    - database


- name: Import Zabbix schema
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "{{ zabbix_source_path }}/database/postgresql/schema.sql"
  become_user: postgres
  delegate_to: "{{ zabbix_db_host }}"
  tags:
    - database


- name: Import Zabbix initial data
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "{{ zabbix_source_path }}/database/postgresql/data.sql"
  become_user: postgres
  delegate_to: "{{ zabbix_db_host }}"
  tags:
    - database


- name: Import Zabbix images
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "{{ zabbix_source_path }}/database/postgresql/images.sql"
  become_user: postgres
  delegate_to: "{{ zabbix_db_host }}"
  tags:
    - database